Sarangbang/backend

src/main/java/sarangbang/site/challengecategory/controller/ChallengeCategoryController.java
src/main/java/sarangbang/site/challengecategory/entity/ChallengeCategory.java
src/main/java/sarangbang/site/challengecategory/repository/ChallengeCategoryRepository.java
src/main/java/sarangbang/site/challengecategory/service/ChallengeCategoryService.java

카테고리조회기능 추가

---

src/main/java/sarangbang/site/challengemember/entity/ChallengeMember.java
src/main/java/sarangbang/site/challengemember/repository/ChallengeMemberRepository.java

- closed: #27 
- Reviewers: 김영준/김영규
- 작업 요약:

challengemember entity/repository 생성

---

src/main/java/sarangbang/site/challenge/controller/ChallengeController.java
src/main/java/sarangbang/site/challengeapplication/controller/ChallengeApplicationController.java
src/main/java/sarangbang/site/challengeapplication/dto/ChallengeApplicationDTO.java
src/main/java/sarangbang/site/challengeapplication/entity/ChallengeApplication.java
src/main/java/sarangbang/site/challengeapplication/repository/ChallengeApplicationRepository.java
src/main/java/sarangbang/site/challengeapplication/service/ChallengeApplicationService.java

- closed: #38 
- Reviewers: @apfp77 
- 작업 요약: 챌린지신청서 도메인 생성

챌린지신청서 도메인 생성

---

src/main/java/sarangbang/site/challengemember/controller/ChallengeMemberController.java
src/main/java/sarangbang/site/challengemember/dto/ChallengeMemberDTO.java
src/main/java/sarangbang/site/challengemember/repository/ChallengeMemberRepository.java
src/main/java/sarangbang/site/challengemember/service/ChallengeMemberService.java

- closed: # #33 
- Reviewers: @SeongriPark @apfp77 
- 작업 요약:

챌린지 식별값 기반 챌린지 멤버 조회

---

src/main/java/sarangbang/site/challenge/controller/ChallengeController.java
src/main/java/sarangbang/site/challenge/repository/ChallengeRepository.java
src/main/java/sarangbang/site/challenge/service/ChallengeService.java

- closed: #57
- Reviewers: @apfp77 @kimyoungjun-dev
- 작업 요약:

챌린지 페이지네이션 추가

---

src/main/java/sarangbang/site/auth/controller/AuthController.java
src/main/java/sarangbang/site/auth/dto/SignupRequestDTO.java
src/main/java/sarangbang/site/auth/exception/EmailAlreadyExistsException.java
src/main/java/sarangbang/site/auth/exception/NicknameAlreadyExistsException.java
src/main/java/sarangbang/site/auth/service/AuthService.java

- closed: #66
- Reviewers: @kyung186 @SeongriPark 
- 작업 요약:

회원가입 및 로그인 에러 세분화

---

src/main/java/sarangbang/site/challengemember/dto/ChallengeMemberResponseDTO.java

- closed: #78 
- Reviewers: 
- 작업 요약:

내가 가입한 챌린지 목록 반환값에 challengeId 추가

---

src/main/java/sarangbang/site/auth/controller/AuthController.java
src/main/java/sarangbang/site/auth/dto/SignupRequestDTO.java
src/main/java/sarangbang/site/auth/service/AuthService.java
src/main/java/sarangbang/site/challenge/controller/ChallengeController.java
src/main/java/sarangbang/site/challenge/dto/ChallengeDTO.java
src/main/java/sarangbang/site/challenge/dto/ChallengeDetailResponseDto.java
src/main/java/sarangbang/site/challenge/dto/ChallengeResponseDto.java
src/main/java/sarangbang/site/challenge/entity/Challenge.java
src/main/java/sarangbang/site/challenge/service/ChallengeService.java
src/main/java/sarangbang/site/challengemember/dto/ChallengeMemberResponseDTO.java
src/main/java/sarangbang/site/global/init/TestDataInitializer.java
src/main/java/sarangbang/site/region/service/RegionService.java
src/main/java/sarangbang/site/user/entity/User.java

- closed: #64 
- Reviewers: @kyung186 @SeongriPark 
- 작업 요약:

회원가입, 챌린지 등록 지역 추가

---

src/main/java/sarangbang/site/challengemember/controller/ChallengeMemberController.java
src/main/java/sarangbang/site/challengemember/dto/ChallengeMemberResponseDTO.java
src/main/java/sarangbang/site/challengemember/service/ChallengeMemberService.java

- 등록한 챌린지 조회 데이터 수정
- swagger 에 배열 추가
- 등록한 챌린지 없을 경우 빈 리스트 반환하도록 수정
- closed: #87 
- Reviewers: 
- 작업 요약:

등록한 챌린지 조회 시 swagger, 반환값 수정

---

src/main/java/sarangbang/site/challenge/controller/ChallengeController.java
src/main/java/sarangbang/site/challenge/repository/ChallengeRepository.java
src/main/java/sarangbang/site/challenge/service/ChallengeService.java

- closed:
- Reviewers: @kimyoungjun-dev  
- 작업 요약: 전체 또는 카테고리 식별 값 기반으로 조회 시 종료되지 않은 챌린지만 반환하도록 변경함

전체 또는 카테고리 식별값 기반으로 조회 시 예정/진행중인 챌린지만 반환

---

src/main/java/sarangbang/site/challengemember/controller/ChallengeMemberController.java
src/main/java/sarangbang/site/challengemember/dto/ChallengeMemberDTO.java
src/main/java/sarangbang/site/challengemember/service/ChallengeMemberService.java
src/main/java/sarangbang/site/challengeverification/repository/ChallengeVerificationRepository.java

- closed: #93 
- Reviewers: @minyeong-lee , @kyung186 
- 작업 요약:

챌린지 멤버 조회 시 반환 값 수정, swagger 추가

---

src/main/java/sarangbang/site/SarangbangApplication.java

- closed:
- Reviewers: @kyung186 @kimyoungjun-dev @minyeong-lee @SeongriPark 
- 작업 요약: 서울 시간으로 고정합니다

프로그램 시간 설정

---

src/main/java/sarangbang/site/global/error/ErrorCode.java
src/main/java/sarangbang/site/global/exception/GlobalExceptionHandler.java

- closed:
- Reviewers: @kyung186 @kimyoungjun-dev @minyeong-lee @SeongriPark
- 작업 요약: 필수 파라미터 누락 시 반환할 예외처리

MissingServletRequestParameterException 전역 처리

---

src/main/java/sarangbang/site/challenge/controller/ChallengeController.java
src/main/java/sarangbang/site/challenge/dto/ChallengePopularityResponseDTO.java
src/main/java/sarangbang/site/challenge/repository/ChallengeRepository.java
src/main/java/sarangbang/site/challenge/service/ChallengeService.java

- closed: #70 
- Reviewers: @kimyoungjun-dev @kyung186 
- 작업 요약:

챌린지 인기순 조회

---

src/main/java/sarangbang/site/security/oauth/OAuth2LoginSuccessHandler.java
src/main/resources/application.yml

- closed:
- Reviewers: 
- 작업 요약: localhost:3000 -> 환경변수로 변경

소셜로그인 성공 시 리다이렉트 환경변수로 변경

---

src/main/java/sarangbang/site/challenge/controller/ChallengeController.java
src/main/java/sarangbang/site/challenge/entity/Challenge.java
src/main/java/sarangbang/site/challenge/service/ChallengeService.java
src/main/java/sarangbang/site/file/enums/ImageType.java
src/main/java/sarangbang/site/file/service/ImageSaveFactory.java
src/main/java/sarangbang/site/file/service/ImageUploadService.java

- closed: #96 
- Reviewers: 
- 작업 요약:

챌린지 이미지 추가

---

src/main/java/sarangbang/site/user/controller/UserController.java
src/main/java/sarangbang/site/user/dto/UserProfileResponseDTO.java
src/main/java/sarangbang/site/user/dto/UserUpdateNicknameRequestDTO.java
src/main/java/sarangbang/site/user/dto/UserUpdatePasswordRequestDTO.java
src/main/java/sarangbang/site/user/entity/User.java
src/main/java/sarangbang/site/user/service/UserService.java

- closed: #110 
- Reviewers: 
- 작업 요약:

user 비밀번호, 닉네임 변경

---

docker-compose.yml
src/main/java/sarangbang/site/challenge/dto/ChallengeResponseDto.java
src/main/java/sarangbang/site/challenge/service/ChallengeService.java
src/main/java/sarangbang/site/challengemember/dto/ChallengeMemberResponseDTO.java
src/main/java/sarangbang/site/challengemember/service/ChallengeMemberService.java
src/main/java/sarangbang/site/file/controller/FileDownloadController.java
src/main/java/sarangbang/site/file/controller/ImageUploadTestController.java
src/main/java/sarangbang/site/file/service/FileStorageService.java
src/main/java/sarangbang/site/file/service/ImageUploadService.java
src/main/java/sarangbang/site/file/service/MinIOFileStorageService.java
src/main/java/sarangbang/site/file/service/S3FileStorageService.java
src/main/java/sarangbang/site/global/config/MinIOConfig.java
src/main/java/sarangbang/site/global/config/S3Config.java
src/main/java/sarangbang/site/global/config/S3PresignerConfig.java
src/main/java/sarangbang/site/global/config/StorageProperties.java
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/application.yml

- closed: #115 
- Reviewers:  @apfp77 
- 작업 요약: S3 public 권한 막고, Presigned URL 적용하여 구현

파일 시스템 Presigned URL 방식 구현

---

src/main/java/sarangbang/site/challenge/service/ChallengeService.java
src/main/java/sarangbang/site/challengemember/service/ChallengeMemberService.java
src/main/java/sarangbang/site/challengeverification/service/ChallengeVerificationService.java

- closed:
- Reviewers: 
- 작업 요약: 저장된 이미지 경로가 없는데 요청하는 현상 수정

이미지 사진이 있는 경우에만 PresignedUrl생성

---

.github/workflows/ci-cd-prod.yml
src/main/java/sarangbang/site/user/service/UserService.java

- closed:
- Reviewers: 
- 작업 요약: ci-cd-prod.yml 코드 수정

ci-cd-prod.yml 코드 수정

---

.github/workflows/ci-cd-prod.yml

- closed:
- Reviewers: 
- 작업 요약:

ci-cd-prod.yml 수정
